version: '2'
services:
  parse-server:
    image: nkeymobile/docker-parse-server
    mem_limit: 256MB
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      DATABASE_URI: $DATABASE_URI
      CLOUD_CODE_MAIN: $CLOUD_CODE_MAIN # /parse/cloud/main.js
      APP_ID: $APP_ID
      MASTER_KEY: $MASTER_KEY
      PARSE_MOUNT: $PARSE_MOUNT # /parse
      COLLECTION_PREFIX: $COLLECTION_PREFIX
      CLIENT_KEY: $CLIENT_KEY
      REST_API_KEY: $REST_API_KEY
      DOTNET_KEY: $DOTNET_KEY
      JAVASCRIPT_KEY: $JAVASCRIPT_KEY
      FILE_KEY: $FILE_KEY
      FACEBOOK_APP_IDS: $FACEBOOK_APP_IDS
      SERVER_URL: $SERVER_URL
      MAX_UPLOAD_SIZE: $MAX_UPLOAD_SIZE # 20mb
      GCM_ID: $GCM_ID
      GCM_KEY: $GCM_KEY
      PRODUCTION_PFX: $PRODUCTION_PFX
      PRODUCTION_PASSPHRASE: $PRODUCTION_PASSPHRASE
      PRODUCTION_BUNDLE_ID: $PRODUCTION_BUNDLE_ID
      PRODUCTION_CERT: $PRODUCTION_CERT # prodCert.pem
      PRODUCTION_KEY: $PRODUCTION_KEY # prodKey.pem
      DEV_PFX: $DEV_PFX
      DEV_PASSPHRASE: $DEV_PASSPHRASE
      DEV_BUNDLE_ID: $DEV_BUNDLE_ID
      DEV_CERT: $DEV_CERT # devCert.pem
      DEV_KEY: $DEV_KEY # devKey.pem
      VERIFY_USER_EMAILS: $VERIFY_USER_EMAILS # 0
      EMAIL_MODULE: $EMAIL_MODULE # "" or "parse-server-simple-mailgun-adapter"
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_DOMAIN: $EMAIL_DOMAIN
      EMAIL_API_KEY: $EMAIL_API_KEY
      EMAIL_DISPLAY_NAME: $EMAIL_DISPLAY_NAME
      EMAIL_REPLY_TO: $EMAIL_REPLY_TO
      EMAIL_VERIFICATION_SUBJECT: $EMAIL_VERIFICATION_SUBJECT
      EMAIL_VERIFICATION_BODY: $EMAIL_VERIFICATION_BODY
      EMAIL_PASSWORD_RESET_SUBJECT: $EMAIL_PASSWORD_RESET_SUBJECT
      EMAIL_PASSWORD_RESET_BODY: $EMAIL_PASSWORD_RESET_BODY
      ENABLE_ANON_USERS: $ENABLE_ANON_USERS # 1
      ALLOW_CLIENT_CLASS_CREATION: $ALLOW_CLIENT_CLASS_CREATION # 1
      PARSE_EXPERIMENTAL_CONFIG_ENABLED: $PARSE_EXPERIMENTAL_CONFIG_ENABLED # 0
      TESTING: $TESTING # 0
      APP_NAME: $APP_NAME
      PUBLIC_SERVER_URL: $PUBLIC_SERVER_URL
      TRUST_PROXY:      $TRUST_PROXY
      S3_ACCESS_KEY:    $S3_ACCESS_KEY
      S3_SECRET_KEY:    $S3_SECRET_KEY
      S3_BUCKET:        $S3_BUCKET
      S3_DIRECT:        $S3_DIRECT
      GCP_PROJECT_ID:   $GCP_PROJECT_ID
      GCP_KEYFILE_PATH: $GCP_KEYFILE_PATH
      GCS_BUCKET:       $GCS_BUCKET
      GCS_DIRECT:       $GCS_DIRECT
      AZURE_ACCOUNT:    $AZURE_ACCOUNT
      AZURE_CONTAINER:  $AZURE_CONTAINER
      AZURE_ACCESS_KEY: $AZURE_ACCESS_KEY
      AZURE_DIRECT:     $AZURE_DIRECT
      VIRTUAL_HOST:      $PARSE_SERVER_VIRTUAL_HOST
      LETSENCRYPT_HOST:  $PARSE_SERVER_LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $PARSE_SERVER_LETSENCRYPT_EMAIL
      GRAPHQL_SUPPORT:  $GRAPHQL_SUPPORT
      GRAPHQL_SCHEMA:   $GRAPHQL_SCHEMA
    volumes:
      - parse-cloud-code:/parse/cloud
      - "./volumes/certs:/certs"

  git:
    image: nkeymobile/docker-parse-server:git
    mem_limit: 64MB
    ports:
      - "2022:22"
    environment:
      PORT: 22
    volumes_from:
      - container: parse-server

  parse-dashboard:
    image: yongjhih/parse-dashboard
    mem_limit: 256MB
    depends_on:
      - parse-server
    environment:
      APP_ID: $APP_ID
      MASTER_KEY: $MASTER_KEY
      APP_NAME: $APP_NAME
      ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
      USER1: $USER1
      USER1_PASSWORD: $USER1_PASSWORD
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
      SERVER_URL: $SERVER_URL
      PARSE_DASHBOARD_SERVER_URL: $SERVER_URL
      PARSE_DASHBOARD_MASTER_KEY: $MASTER_KEY
      PARSE_DASHBOARD_APP_ID: $APP_ID
      PARSE_DASHBOARD_APP_NAME: $APP_NAME
      PARSE_DASHBOARD_USER_ID: $USER1
      PARSE_DASHBOARD_USER_PASSWORD: $USER1_PASSWORD
      PARSE_DASHBOARD_CONFIG: $PARSE_DASHBOARD_CONFIG
      MOUNT_PATH: $PARSE_DASHBOARD_MOUNT_PATH
      TRUST_PROXY: $PARSE_DASHBOARD_TRUST_PROXY
      VIRTUAL_HOST:      $PARSE_DASHBOARD_VIRTUAL_HOST
      LETSENCRYPT_HOST:  $PARSE_DASHBOARD_LETSENCRYPT_HOST
      LETSENCRYPT_EMAIL: $PARSE_DASHBOARD_LETSENCRYPT_EMAIL
      PORT: 4040
    ports:
      - "4040:4040"

  nginx:
    image: nginx
    container_name: nginx
    mem_limit: 128MB
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    mem_limit: 64MB
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - container: nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    mem_limit: 64MB
    volumes_from:
      - container: nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

volumes:
  parse-cloud-code:

# vim:set et ts=2 sw=2:
